[phases.setup]
nixPkgs = ["python39Full", "python39Packages.pip", "gcc", "curl", "wget"]

[variables]
PYTHON_VERSION = "3.9"

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt", "pip install flask flask-socketio"]

[start]
cmd = "python app.py"
